-- =============================================================================
-- VisionTrack AI — Supabase Database Schema
-- Run this script in your Supabase project's SQL Editor.
-- =============================================================================

-- 1. Table for individual object detections & tracking logs
create table if not exists public.detections (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    session_id text not null,
    track_id integer default -1,
    label text not null,
    confidence real,
    x1 integer,
    y1 integer,
    x2 integer,
    y2 integer,
    group_name text default 'other'
);

-- 2. Table for session summary aggregates
create table if not exists public.sessions (
    id text primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    total_objects integer default 0,
    people_count integer default 0,
    vehicle_count integer default 0,
    animal_count integer default 0,
    frames_count integer default 0,
    model_name text default 'yolov8n'
);

-- 3. Indexes for high-speed queries
create index if not exists idx_detections_session_id on public.detections(session_id);
create index if not exists idx_detections_label on public.detections(label);
create index if not exists idx_detections_created_at on public.detections(created_at desc);

-- 4. Enable Row Level Security (RLS)
alter table public.detections enable row level security;
alter table public.sessions enable row level security;

-- 5. Policies allowing insert and read with your API key
create policy "Allow all operations for anon/service role"
on public.detections
for all
using (true)
with check (true);

create policy "Allow all operations for sessions"
on public.sessions
for all
using (true)
with check (true);
